/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 12-may-2011, 17:13:41
 */
package Visual;

import gato_raton.Gato_Raton;
import javax.swing.JOptionPane;

/**
 *
 * @author harold
 */
public class MainFrame extends javax.swing.JFrame {

    private Tablero mesa;
    private Gato_Raton controler; 
    

    /** Creates new form MainFrame */
    public MainFrame() {

        initComponents();
        this.setTitle("Gato y Raton");
        setSize(485, 535);
        this.setLayout(null);
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        controler = new Gato_Raton();
        mesa = new Tablero(controler);
        this.add(mesa);
        mesa.setBounds(0, 0, 480, 480);
        mesa.addMouseListener(mesa);
        CrearPartida();
        
        // this.setSize(580,580);
//        jPanel1.setOpaque(false);
//        jPanel1.setVisible(true);
//        fondo = new JLabel();
//        fondo.setIcon(new ImageIcon("imagenes/Tablero.jpg"));
//        jPanel1.add(fondo);

        //  fondo.setBounds(0,0,480,480);

    }

     public void CrearPartida() {
        Object[] modo = {"Raton", "Gato"};
        Object select = JOptionPane.showInputDialog(this, "Seleccione con quien quiere jugar", null, WIDTH, null, modo, true);
        this.setRootPaneCheckingEnabled(true);
        if (select.equals("Raton")) {
            controler.setModoRata(false);
            controler.generarTablero();
        } else {
            controler.setModoRata(true);
            controler.generarTablero();
           
                controler.GenerarArbolDeJugadas();
            
        }
        mesa.paint();
        mesa.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Juego nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Terminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CrearPartida();
       
       
        mesa.paint();
        mesa.repaint();
  
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
